
import json

broken_names = [
    "?hl?ns AB", "24 s?vres", "A?roport Marseille Provence", 
    "AIESC - Associa??o Internacional de Experi?ncia e Sucesso do Cliente", 
    "ALDI ESPA?A", "ALDI S?D HOLDING", "Ar?elik Hitachi Home Appliances", 
    "Atacad?o", "Auchan Retail Magyarorsz?g", "Auchan Retail Rom?nia", 
    "AUDERE \"Ensemble, d?veloppons votre marque\"", 
    "B?nh vi?n ?a Khoa H?u Ngh? 103 Y?n B?i", "B&B Hotels Espa?a y Portugal", 
    "BigC Vi?t Nam", "Branding | retail |corporate | design dexp?rience", 
    "C?NG TY C? PH?N ??U T? TH? GI?I DI ??NG", "C?ng ty c? ph?n Bibomart (Bibomart JSC)", 
    "C?ng ty C? ph?n S?i Bi?n Trung Th?c", "C?ng ty C? ph?n Si?u th? Vincommerce", 
    "C?ng ty C? ph?n Si?u th? VinMart", "C?ng ty ch?ng kho?n NaviBank", 
    "C?ng ty CP Nghi?n c?u v? S?n xu?t Vinsmart", "C?ng Ty CP Th? Gi?i Di ??ng", 
    "C?ng ty TNHH Ki?m To?n v? T? V?n A&C", "C?NG TY TNHH TH??NG M?I V? D?CH V? THAVICO", 
    "Carrefour Espa?a", "Carrefour Rom?nia", "Carrefour Supermarch?s France", 
    "Ch?ng kho?n Ki?n Long", "Consumer Product Division -- LOr?al Paris International", 
    "D Maris Bay Dat?a Peninsula", "D?cathlon Canada", "Decathlon Rom?nia", 
    "Du Pareil Au M?me", "El Corte Ingl?s", "Frantz?n Group", "G?mo", 
    "gfm  Schweizerische Gesellschaft f?r Marketing", 
    "Grand H?tel Stockholm, Sweden", "Groupe Cr?O", "H?rklinikken", 
    "Heineken Espa?a, S.A.", "Herm?s", "Hunkem?ller", "Hunkem?ller International BV", 
    "iLAW_C?ng b?n chia s? m?i v?n ?? ph?p lu?t", "Import Parf?merie", 
    "Institut Fran?ais de la Mode", "InterContinental Gen?ve", 
    "ISAL - Institut Sup?rieur des Arts et du Luxe", "J?sto", "Jer?nimo Martins", 
    "K?rcher Viet Nam", "Kr?fel NV", "L'Or?al", "L'Or?al Consumer Products Division", 
    "L'Or?al Thailand", "La Caisse (Caisse de d?p?t et placement du Qu?bec)", 
    "La Cha?ne des R?tisseurs", "La Europea M?xico", "La Mar by Gast?n Acurio", 
    "La Monta?ita Co-op Food Market", "Lagard?re", "Lagard?re Travel Retail", 
    "Le M?ridien Bangkok", "Le M?ridien Khao Lak Resort & Spa", 
    "Le M?ridien Phuket Mai Khao Beach Resort", "Leroy Merlin - Espa?a", 
    "LES ETINCELLES h?tels, chalets & r?sidences", "Lindt & Spr?ngli", 
    "Livotec - Tr? trung th?ng minh, s?ng kh?e m?i ng?y", 
    "LOr?al Thailand, Myanmar, Laos and Cambodia", "M?venpick Hotels & Resorts", 
    "M?venpick Resort Khao Yai & M?venpick Residences Ekkamai Bangkok", 
    "Maison Johan?s Boub?e", "Makro Autoservicio Mayorista S.A Espa?a", 
    "Makro Espa?a", "Maxidi - Ch? Ki?u M?i", "MEDICARPE D?fi Sant? Pour Tous", 
    "Mercedes Vietnamstar Phu? My? H?ng", "METRO Magyarorsz?g", 
    "Metro T?rkiye", "METRO T?rkiye", "Minist?re de l'Europe et des Affaires ?trang?res", 
    "Minist?re des Affaires sociales, du Travail et de la Solidarit?", 
    "Mo?t Hennessy", "Mondel?z International", "natur?O", "Ng?n h?ng SHB", 
    "Nguy?n Xu?n V? Kovitech", "Nutifood Vi?t Nam", "NutiFood Vi?t Nam", 
    "PA?PURI", "Paradies Lagard?re", "Paula's Choice Vi?t Nam", 
    "PSA Peugeot Citro?n", "Quir?nprevenci?n", "R?dl & Partner", "RD Sa?de", 
    "S?o Paulo, Brazil", "Sa?d Business School, University of Oxford", 
    "Sabrina M?naco - Coach & Human Development", "Soci?t? G?n?rale", 
    "Supeco Rom?nia", "Swiss?tel Nankai Osaka", "Swiss?tel Resort Phuket", 
    "T?NG C?NG TY C? PH?N TH??NG M?I X?Y D?NG (WTO)", "T?p ?o?n T?n Hi?p Ph?t", 
    "T?V Rheinland Thailand Ltd.", "T?V S?D", "TEKO Vi?t Nam", 
    "Tesco Magyarorsz?g", "The Est?e Lauder Companies Inc.", "The Pok?mon Company", 
    "TTC Land - D?? A?n Cao C??p", "TTC Ph? Qu?c (Toan Hai Van)", 
    "Tuy?n d?ng FPT Telecom (fptjobs.com)", "V?n An Co., Ltd", 
    "Van Phuc City - Khu ?? th? V?n Ph?c", 
    "Vietbank (Ng?n H?ng TMCP Vi?t Nam Th??ng T?n)", 
    "Vietnam International Bank (VIB) - Ng?n H?ng Qu?c T?", "Villa Eug?nie", 
    "Vovan & Associ?s", "W?rth Group", "Walmart de M?xico y Centroam?rica"
]

corrections = {
    "?hl?ns AB": "Ahlens AB",
    "24 s?vres": "24 sevres",
    "A?roport Marseille Provence": "Aeroport Marseille Provence",
    "AIESC - Associa??o Internacional de Experi?ncia e Sucesso do Cliente": "AIESC - Associacao Internacional de Experiencia e Sucesso do Cliente",
    "ALDI ESPA?A": "ALDI ESPANA",
    "ALDI S?D HOLDING": "ALDI SUD HOLDING",
    "Ar?elik Hitachi Home Appliances": "Arcelik Hitachi Home Appliances",
    "Atacad?o": "Atacadao",
    "Auchan Retail Magyarorsz?g": "Auchan Retail Magyarorszag",
    "Auchan Retail Rom?nia": "Auchan Retail Romania",
    "AUDERE \"Ensemble, d?veloppons votre marque\"": "AUDERE \"Ensemble, developpons votre marque\"",
    "B?nh vi?n ?a Khoa H?u Ngh? 103 Y?n B?i": "Benh vien Da Khoa Huu Nghe 103 Yen Bai",
    "B&B Hotels Espa?a y Portugal": "B&B Hotels Espana y Portugal",
    "BigC Vi?t Nam": "BigC Viet Nam",
    "Branding | retail |corporate | design dexp?rience": "Branding | retail | corporate | design d'experience",
    "C?NG TY C? PH?N ??U T? TH? GI?I DI ??NG": "CONG TY CO PHAN DAU TU THE GIOI DI DONG",
    "C?ng ty c? ph?n Bibomart (Bibomart JSC)": "Cong ty co phan Bibomart (Bibomart JSC)",
    "C?ng ty C? ph?n S?i Bi?n Trung Th?c": "Cong ty Co phan Soi Bien Trung Thuc",
    "C?ng ty C? ph?n Si?u th? Vincommerce": "Cong ty Co phan Sieu thi Vincommerce",
    "C?ng ty C? ph?n Si?u th? VinMart": "Cong ty Co phan Sieu thi VinMart",
    "C?ng ty ch?ng kho?n NaviBank": "Cong ty chung khoan NaviBank",
    "C?ng ty CP Nghi?n c?u v? S?n xu?t Vinsmart": "Cong ty CP Nghien cuu va San xuat Vinsmart",
    "C?ng Ty CP Th? Gi?i Di ??ng": "Cong Ty CP The Gioi Di Dong",
    "C?ng ty TNHH Ki?m To?n v? T? V?n A&C": "Cong ty TNHH Kiem Toan va Tu Van A&C",
    "C?NG TY TNHH TH??NG M?I V? D?CH V? THAVICO": "CONG TY TNHH THUONG MAI VA DICH VU THAVICO",
    "Carrefour Espa?a": "Carrefour Espana",
    "Carrefour Rom?nia": "Carrefour Romania",
    "Carrefour Supermarch?s France": "Carrefour Supermarches France",
    "Ch?ng kho?n Ki?n Long": "Chung khoan Kien Long",
    "Consumer Product Division -- LOr?al Paris International": "Consumer Product Division -- L'Oreal Paris International",
    "D Maris Bay Dat?a Peninsula": "D Maris Bay Datca Peninsula",
    "D?cathlon Canada": "Decathlon Canada",
    "Decathlon Rom?nia": "Decathlon Romania",
    "Du Pareil Au M?me": "Du Pareil Au Meme",
    "El Corte Ingl?s": "El Corte Ingles",
    "Frantz?n Group": "Frantzen Group",
    "G?mo": "Gemo",
    "gfm  Schweizerische Gesellschaft f?r Marketing": "gfm - Schweizerische Gesellschaft fur Marketing",
    "Grand H?tel Stockholm, Sweden": "Grand Hotel Stockholm, Sweden",
    "Groupe Cr?O": "Groupe CreO",
    "H?rklinikken": "Harklinikken",
    "Heineken Espa?a, S.A.": "Heineken Espana, S.A.",
    "Herm?s": "Hermes",
    "Hunkem?ller": "Hunkemoller",
    "Hunkem?ller International BV": "Hunkemoller International BV",
    "iLAW_C?ng b?n chia s? m?i v?n ?? ph?p lu?t": "iLAW_Cong ban chia se moi van de phap luat",
    "Import Parf?merie": "Import Parfumerie",
    "Institut Fran?ais de la Mode": "Institut Francais de la Mode",
    "InterContinental Gen?ve": "InterContinental Geneve",
    "ISAL - Institut Sup?rieur des Arts et du Luxe": "ISAL - Institut Superieur des Arts et du Luxe",
    "J?sto": "Justo",
    "Jer?nimo Martins": "Jeronimo Martins",
    "K?rcher Viet Nam": "Karcher Viet Nam",
    "Kr?fel NV": "Krefel NV",
    "L'Or?al": "L'Oreal",
    "L'Or?al Consumer Products Division": "L'Oreal Consumer Products Division",
    "L'Or?al Thailand": "L'Oreal Thailand",
    "La Caisse (Caisse de d?p?t et placement du Qu?bec)": "La Caisse (Caisse de depot et placement du Quebec)",
    "La Cha?ne des R?tisseurs": "La Chaine des Rotisseurs",
    "La Europea M?xico": "La Europea Mexico",
    "La Mar by Gast?n Acurio": "La Mar by Gaston Acurio",
    "La Monta?ita Co-op Food Market": "La Montanita Co-op Food Market",
    "Lagard?re": "Lagardere",
    "Lagard?re Travel Retail": "Lagardere Travel Retail",
    "Le M?ridien Bangkok": "Le Meridien Bangkok",
    "Le M?ridien Khao Lak Resort & Spa": "Le Meridien Khao Lak Resort & Spa",
    "Le M?ridien Phuket Mai Khao Beach Resort": "Le Meridien Phuket Mai Khao Beach Resort",
    "Leroy Merlin - Espa?a": "Leroy Merlin - Espana",
    "LES ETINCELLES h?tels, chalets & r?sidences": "LES ETINCELLES hotels, chalets & residences",
    "Lindt & Spr?ngli": "Lindt & Sprungli",
    "Livotec - Tr? trung th?ng minh, s?ng kh?e m?i ng?y": "Livotec - Tre trung thong minh, song khoe moi ngay",
    "LOr?al Thailand, Myanmar, Laos and Cambodia": "L'Oreal Thailand, Myanmar, Laos and Cambodia",
    "M?venpick Hotels & Resorts": "Movenpick Hotels & Resorts",
    "M?venpick Resort Khao Yai & M?venpick Residences Ekkamai Bangkok": "Movenpick Resort Khao Yai & Movenpick Residences Ekkamai Bangkok",
    "Maison Johan?s Boub?e": "Maison Johanes Boubee",
    "Makro Autoservicio Mayorista S.A Espa?a": "Makro Autoservicio Mayorista S.A Espana",
    "Makro Espa?a": "Makro Espana",
    "Maxidi - Ch? Ki?u M?i": "Maxidi - Cho Kieu Moi",
    "MEDICARPE D?fi Sant? Pour Tous": "MEDICARPE Defi Sante Pour Tous",
    "Mercedes Vietnamstar Phu? My? H?ng": "Mercedes Vietnamstar Phu My Hung",
    "METRO Magyarorsz?g": "METRO Magyarorszag",
    "Metro T?rkiye": "Metro Turkiye",
    "METRO T?rkiye": "METRO Turkiye",
    "Minist?re de l'Europe et des Affaires ?trang?res": "Ministere de l'Europe et des Affaires etrangeres",
    "Minist?re des Affaires sociales, du Travail et de la Solidarit?": "Ministere des Affaires sociales, du Travail et de la Solidarite",
    "Mo?t Hennessy": "Moet Hennessy",
    "Mondel?z International": "Mondelez International",
    "natur?O": "naturO",
    "Ng?n h?ng SHB": "Ngan hang SHB",
    "Nguy?n Xu?n V? Kovitech": "Nguyen Xuan Vu Kovitech",
    "Nutifood Vi?t Nam": "Nutifood Viet Nam",
    "NutiFood Vi?t Nam": "NutiFood Viet Nam",
    "PA?PURI": "PAÑPURI",
    "Paradies Lagard?re": "Paradies Lagardere",
    "Paula's Choice Vi?t Nam": "Paula's Choice Viet Nam",
    "PSA Peugeot Citro?n": "PSA Peugeot Citroen",
    "Quir?nprevenci?n": "Quironprevencion",
    "R?dl & Partner": "Rodl & Partner",
    "RD Sa?de": "RD Saude",
    "S?o Paulo, Brazil": "Sao Paulo, Brazil",
    "Sa?d Business School, University of Oxford": "Said Business School, University of Oxford",
    "Sabrina M?naco - Coach & Human Development": "Sabrina Monaco - Coach & Human Development",
    "Soci?t? G?n?rale": "Societe Generale",
    "Supeco Rom?nia": "Supeco Romania",
    "Swiss?tel Nankai Osaka": "Swissotel Nankai Osaka",
    "Swiss?tel Resort Phuket": "Swissotel Resort Phuket",
    "T?NG C?NG TY C? PH?N TH??NG M?I X?Y D?NG (WTO)": "TONG CONG TY CO PHAN THUONG MAI XAY DUNG (WTO)",
    "T?p ?o?n T?n Hi?p Ph?t": "Tap doan Tan Hiep Phat",
    "T?V Rheinland Thailand Ltd.": "TUV Rheinland Thailand Ltd.",
    "T?V S?D": "TUV SUD",
    "TEKO Vi?t Nam": "TEKO Viet Nam",
    "Tesco Magyarorsz?g": "Tesco Magyarorszag",
    "The Est?e Lauder Companies Inc.": "The Estee Lauder Companies Inc.",
    "The Pok?mon Company": "The Pokemon Company",
    "TTC Land - D?? A?n Cao C??p": "TTC Land - Du An Cao Cap",
    "TTC Ph? Qu?c (Toan Hai Van)": "TTC Phu Quoc (Toan Hai Van)",
    "Tuy?n d?ng FPT Telecom (fptjobs.com)": "Tuyen dung FPT Telecom (fptjobs.com)",
    "V?n An Co., Ltd": "Van An Co., Ltd",
    "Van Phuc City - Khu ?? th? V?n Ph?c": "Van Phuc City - Khu do thi Van Phuc",
    "Vietbank (Ng?n H?ng TMCP Vi?t Nam Th??ng T?n)": "Vietbank (Ngan Hang TMCP Viet Nam Thuong Tin)",
    "Vietnam International Bank (VIB) - Ng?n H?ng Qu?c T?": "Vietnam International Bank (VIB) - Ngan Hang Quoc Te",
    "Villa Eug?nie": "Villa Eugenie",
    "Vovan & Associ?s": "Vovan & Associes",
    "W?rth Group": "Wurth Group",
    "Walmart de M?xico y Centroam?rica": "Walmart de Mexico y Centroamerica"
}

sql_statements = []
for broken, clean in corrections.items():
    # Escape single quotes for SQL
    b_esc = broken.replace("'", "''")
    c_esc = clean.replace("'", "''")
    sql_statements.append(f"INSERT INTO encoding_correction_staging (broken_name, suggested_name) VALUES ('{b_esc}', '{c_esc}') ON CONFLICT (broken_name) DO UPDATE SET suggested_name = EXCLUDED.suggested_name;")

with open("populate_mapping.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(sql_statements))

print(f"Generated {len(sql_statements)} INSERT statements in populate_mapping.sql")
