import csv
import json
import os
import urllib.request
import time
import sys
import io

# Set stdout to utf-8
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

url_base = "https://ddeqeaicjyrevqdognbn.supabase.co/rest/v1/"
key = "sb_publishable_UDxVdxP4fSEZmcjx-q_2DA_jzLA8mdZ"
folder = r"C:\HR ATS_CGC project\Industry issue"
files = [f for f in os.listdir(folder) if f.endswith('.csv')]

def run_sql(query):
    sql_url = "https://ddeqeaicjyrevqdognbn.supabase.co/rest/v1/rpc/execute_sql" # This is a guess, usually we use the tool
    # Better to use the tool via a separate call if needed, but here I'll try to use the Tool from the agent
    # Oh wait, this script is running locally, it doesn't have access to the agent's tools.
    # I will generate the SQL and print it, then the agent (me) will execute it.
    pass

# Step 1: Get headers from first file
first_file = os.path.join(folder, files[0])
with open(first_file, mode='r', encoding='utf-8-sig', errors='replace') as f:
    reader = csv.reader(f)
    original_headers = next(reader)
    original_headers = [h.strip() for h in original_headers if h.strip()]

# Clean headers for SQL
def clean_col(h):
    return h.replace('/', '_').replace(' ', '_').replace('.', '_').replace('-', '_').replace('(', '').replace(')', '')

clean_headers = [clean_col(h) for h in original_headers]

# Step 2: Generate CREATE TABLE
create_sql = "DROP TABLE IF EXISTS public.industry_issue;\n"
create_sql += "CREATE TABLE public.industry_issue (\n"
create_sql += "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
cols = []
for h in clean_headers:
    cols.append(f'  "{h}" TEXT')
create_sql += ",\n".join(cols)
create_sql += "\n);"

with open('create_table.sql', 'w', encoding='utf-8') as f:
    f.write(create_sql)

print("SQL saved to create_table.sql")
